"""Initial migration

Revision ID: 07a487622555
Revises: 
Create Date: 2026-02-25 16:37:00.605329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a487622555'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conjoint_survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('conjoint_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['conjoint_survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conjoint_respondent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['conjoint_survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conjoint_choice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('respondent_id', sa.Integer(), nullable=False),
    sa.Column('task_number', sa.Integer(), nullable=False),
    sa.Column('option_a', sa.JSON(), nullable=False),
    sa.Column('option_b', sa.JSON(), nullable=False),
    sa.Column('chosen_option', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['respondent_id'], ['conjoint_respondent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conjoint_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['conjoint_attribute.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('answers_json', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['survey_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'survey_id', name='uq_user_survey_once')
    )
    with op.batch_alter_table('survey_submission', schema=None) as batch_op:
        batch_op.create_index('ix_submission_survey_id', ['survey_id'], unique=False)
        batch_op.create_index('ix_submission_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_submission', schema=None) as batch_op:
        batch_op.drop_index('ix_submission_user_id')
        batch_op.drop_index('ix_submission_survey_id')

    op.drop_table('survey_submission')
    op.drop_table('conjoint_level')
    op.drop_table('conjoint_choice')
    op.drop_table('survey')
    op.drop_table('conjoint_respondent')
    op.drop_table('conjoint_attribute')
    op.drop_table('survey_user')
    op.drop_table('conjoint_survey')
    op.drop_table('company')
    # ### end Alembic commands ###
